'use client';

import { ChevronRight, Phone, RefreshCw, Users, X } from 'lucide-react';
import { useState } from 'react';

export function MapCallersCard({ alerts, theme, onSelectAlert }) {
  const sorted = [...alerts].sort((a, b) => a.dist - b.dist);
  return <div className="absolute top-5 left-5 z-[500] w-[300px] max-w-[calc(100%-40px)] max-h-[calc(100%-40px)] bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden flex flex-col">
    <div className="p-4 border-b border-gray-100 shrink-0"><div className="flex items-center gap-2 text-sm font-bold"><Users className="h-4 w-4" style={{ color: theme.hex }} />{theme.label} callers</div><p className="text-xs text-gray-500 mt-1">{alerts.length} active incident{alerts.length !== 1 ? 's' : ''} on this map</p></div>
    <div className="overflow-y-auto divide-y divide-gray-100">{sorted.length === 0 ? <div className="p-5 text-sm text-gray-500">No active callers at the moment.</div> : sorted.map(alert => <button type="button" key={alert.id} onClick={() => onSelectAlert(alert.id)} className="w-full text-left p-3 flex items-center gap-3 hover:bg-gray-50 transition"><span className="h-8 w-8 rounded-full grid place-items-center shrink-0 text-white text-xs font-bold font-mono" style={{ backgroundColor: theme.hex }}>{alert.type[0].toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold truncate">{alert.caller}</span><span className="block text-xs text-gray-500 truncate">{alert.barangay} · {alert.dist} km</span></span><span className={`status-pill ${alert.status}`}>{alert.status}</span></button>)}</div>
  </div>;
}

export function IncidentCard({ alert, theme, now, onAccept, onResolve }) {
  return <div className="incident-card absolute top-5 right-5 w-[350px] max-w-[calc(100%-40px)] bg-white rounded-xl shadow-2xl border border-gray-100 overflow-hidden z-[500]">
    <div className="p-4 border-b flex items-start justify-between" style={{ backgroundColor: theme.softHex }}><div><div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: theme.hex }}>{theme.label} · ES-{String(alert.id).padStart(4, '0')}</div><h2 className="font-bold text-xl mt-1">{alert.caller}</h2></div><span className={`status-pill ${alert.status}`}>{alert.status}</span></div>
    <div className="p-5 space-y-4"><Info label="Location"><span className="font-semibold">{alert.barangay}</span> <span className="text-gray-400">({alert.dist} km)</span></Info><Info label="Contact"><a className="font-semibold text-gray-900 hover:underline" href={`tel:${alert.phone}`}><Phone className="inline h-3.5 w-3.5 mr-1" />{alert.phone}</a></Info><Info label="Situation report"><div className="bg-gray-50 rounded-lg border p-3 text-sm leading-6">{alert.description}</div></Info><div className="text-xs text-gray-400">Reported {Math.max(0, Math.floor((now - alert.reportedAt) / 60000))} minutes ago</div><div className="pt-4 border-t grid grid-cols-2 gap-3">{alert.status === 'pending' ? <button onClick={onAccept} className="primary-btn col-span-2 text-white" style={{ backgroundColor: theme.hex }}>Dispatch Units</button> : <><button disabled className="secondary-btn justify-center opacity-60">Units Dispatched</button><button onClick={onResolve} className="primary-btn justify-center text-white" style={{ backgroundColor: theme.hex }}>Move to History</button></>}</div></div>
  </div>;
}

export function HistoryView({ alerts, theme }) {
  const [openId, setOpenId] = useState(null);
  const sorted = [...alerts].sort((a, b) => (b.resolvedAt || 0) - (a.resolvedAt || 0));
  const openAlert = sorted.find(alert => alert.id === openId);
  return <div className="flex-1 overflow-y-auto p-8"><div className="max-w-5xl mx-auto"><div className="mb-6"><h2 className="text-2xl font-bold">Incident History</h2><p className="text-sm text-gray-500 mt-1">Resolved incidents for this department. Select a record to view its full details.</p></div><div className="bg-white border rounded-xl overflow-hidden shadow-sm">{!sorted.length ? <div className="p-16 text-center text-gray-500">No resolved incidents yet.</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-500 text-xs uppercase"><tr><th className="px-5 py-4">ID</th><th className="px-5 py-4">Caller</th><th className="px-5 py-4">Location</th><th className="px-5 py-4">Reported</th><th className="px-5 py-4">Resolved</th><th className="px-5 py-4">Status</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y">{sorted.map(alert => <tr key={alert.id} onClick={() => setOpenId(alert.id)} className="hover:bg-gray-50 cursor-pointer"><td className="px-5 py-4 font-mono text-gray-500">ES-{String(alert.id).padStart(4, '0')}</td><td className="px-5 py-4 font-semibold">{alert.caller}</td><td className="px-5 py-4 text-gray-600">{alert.barangay}</td><td className="px-5 py-4 text-gray-500">{new Date(alert.reportedAt).toLocaleString()}</td><td className="px-5 py-4 text-gray-500">{new Date(alert.resolvedAt).toLocaleString()}</td><td className="px-5 py-4"><span className="status-pill resolved">Resolved</span></td><td className="px-5 py-4 text-gray-400"><ChevronRight className="h-4 w-4" /></td></tr>)}</tbody></table></div>}</div></div>{openAlert && <HistoryDetailModal alert={openAlert} theme={theme} onClose={() => setOpenId(null)} />}</div>;
}

function HistoryDetailModal({ alert, theme, onClose }) {
  const durationMin = Math.max(0, Math.round((alert.resolvedAt - alert.reportedAt) / 60000));
  return <div className="modal-backdrop" onClick={onClose}><div className="modal-panel" onClick={event => event.stopPropagation()}><div className="p-4 border-b flex items-start justify-between" style={{ backgroundColor: theme.softHex }}><div><div className="text-[10px] font-bold uppercase tracking-wider" style={{ color: theme.hex }}>{theme.label} · ES-{String(alert.id).padStart(4, '0')}</div><h2 className="font-bold text-xl mt-1">{alert.caller}</h2></div><button onClick={onClose} className="h-8 w-8 rounded-lg grid place-items-center hover:bg-white/70 text-gray-500" aria-label="Close details"><X className="h-4 w-4" /></button></div><div className="p-5 space-y-4"><Info label="Location"><span className="font-semibold">{alert.barangay}</span> <span className="text-gray-400">({alert.dist} km)</span></Info><Info label="Contact"><a className="font-semibold text-gray-900 hover:underline" href={`tel:${alert.phone}`}><Phone className="inline h-3.5 w-3.5 mr-1" />{alert.phone}</a></Info><Info label="Situation report"><div className="bg-gray-50 rounded-lg border p-3 text-sm leading-6">{alert.description}</div></Info><div className="grid grid-cols-2 gap-4"><Info label="Reported"><span className="text-sm">{new Date(alert.reportedAt).toLocaleString()}</span></Info><Info label="Resolved"><span className="text-sm">{new Date(alert.resolvedAt).toLocaleString()}</span></Info></div><Info label="Time to resolve"><span className="text-sm font-semibold">{durationMin} minute{durationMin !== 1 ? 's' : ''}</span></Info><div className="pt-4 border-t"><span className="status-pill resolved">Resolved</span></div></div></div></div>;
}

export function SettingsView({ settings, toggle, theme, session, resetData }) {
  return <div className="flex-1 overflow-y-auto p-8"><div className="max-w-5xl mx-auto"><h2 className="text-2xl font-bold">Console Settings</h2><p className="text-sm text-gray-500 mt-1 mb-7">Manage dispatcher preferences and locally stored console data.</p><div className="grid md:grid-cols-2 gap-6"><SettingsCard title="Responder station" desc="Current station configuration."><Row label="Station" value="E-Sagip Main Dispatch" /><Row label="Coverage" value="10 km response radius" /></SettingsCard><SettingsCard title="Dispatch preferences" desc="Control how this console behaves."><Toggle label="Alert sound" desc="Play a sound for new caller alerts" value={settings.sound} onClick={() => toggle('sound')} theme={theme} /><Toggle label="Auto refresh" desc="Refresh incident data automatically" value={settings.refresh} onClick={() => toggle('refresh')} theme={theme} /></SettingsCard><SettingsCard title="Notifications" desc="Operational notices shown in the console."><Toggle label="Status updates" desc="Show accepted and resolved activity" value={settings.status} onClick={() => toggle('status')} theme={theme} /><Toggle label="System notices" desc="Connection and service messages" value={settings.system} onClick={() => toggle('system')} theme={theme} /></SettingsCard><SettingsCard title="Session" desc="Current responder account."><Row label="Dispatcher" value={session.name || session.email} /><Row label="Department" value={theme.label} /><Row label="Connection" value="Live / Connected" green /></SettingsCard><SettingsCard title="Incident records" desc="Manage data stored for this console."><button onClick={resetData} className="secondary-btn"><RefreshCw className="h-4 w-4" />Reset incident records</button></SettingsCard></div></div></div>;
}

function Info({ label, children }) { return <div><div className="text-[11px] font-medium text-gray-500 mb-1">{label}</div>{children}</div>; }
function SettingsCard({ title, desc, children }) { return <section className="bg-white rounded-xl border p-6 shadow-sm"><h3 className="font-bold text-lg">{title}</h3><p className="text-sm text-gray-500 mt-1 mb-5">{desc}</p><div className="divide-y">{children}</div></section>; }
function Row({ label, value, green }) { return <div className="py-3 flex items-center justify-between gap-5"><div className="text-sm font-semibold">{label}</div><div className={`text-sm ${green ? 'text-green-600 font-medium' : 'text-gray-500'} text-right`}>{value}</div></div>; }
function Toggle({ label, desc, value, onClick, theme }) { return <div className="py-3 flex items-center justify-between gap-5"><div><div className="text-sm font-semibold">{label}</div><div className="text-xs text-gray-500 mt-1">{desc}</div></div><button onClick={onClick} aria-label={`Toggle ${label}`} className="h-6 w-10 rounded-full p-1 transition" style={{ backgroundColor: value ? theme.hex : '#E5E7EB' }}><span className={`block h-4 w-4 rounded-full bg-white shadow transition ${value ? 'translate-x-4' : 'translate-x-0'}`} /></button></div>; }
