'use client';
import { useEffect, useRef } from 'react';
import { STATION } from '../lib/mockData';
export default function IncidentMap({ alerts, theme, selectedId, onSelectAlert }) {
  const mapRef=useRef(null), mapInstanceRef=useRef(null), markersRef=useRef({}), stationLayerRef=useRef(null);
  useEffect(()=>{ let cancelled=false; const setup=async()=>{ if(!document.getElementById('leaflet-css')){const link=document.createElement('link');link.id='leaflet-css';link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(link);} const leaflet=await import('leaflet');const L=leaflet.default||leaflet;if(cancelled||!mapRef.current)return;
    if(!mapInstanceRef.current){const map=L.map(mapRef.current,{zoomControl:false}).setView([STATION.lat,STATION.lng],13);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,minZoom:10,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);mapInstanceRef.current=map;}
    const map=mapInstanceRef.current;if(stationLayerRef.current)map.removeLayer(stationLayerRef.current);const stationGroup=L.layerGroup().addTo(map);L.circle([STATION.lat,STATION.lng],{radius:3000,color:theme.hex,weight:2,dashArray:'4 4',fillOpacity:.04}).addTo(stationGroup);const stationHtml=`<div style="width:20px;height:20px;border-radius:50%;background:white;border:3px solid ${theme.hex};position:relative"><div style="position:absolute;inset:2px;border-radius:50%;background:${theme.hex}"></div></div>`;L.marker([STATION.lat,STATION.lng],{icon:L.divIcon({className:'',html:stationHtml,iconSize:[20,20],iconAnchor:[10,10]})}).addTo(stationGroup).bindTooltip(STATION.name,{direction:'top'});stationLayerRef.current=stationGroup;
    Object.values(markersRef.current).forEach(m=>map.removeLayer(m));markersRef.current={};alerts.forEach(a=>{const selected=a.id===selectedId,size=selected?34:26,bg=a.status==='resolved'?'#9CA3AF':theme.hex;const html=`<div style="width:${size}px;height:${size}px;background:${bg};color:white;border-radius:50%;border:2px solid white;display:flex;align-items:center;justify-content:center;font-weight:700;font-family:monospace;box-shadow:${selected?`0 0 0 5px ${theme.hex}44,`:''}0 3px 10px #0003">${a.type[0].toUpperCase()}</div>`;const marker=L.marker([a.lat,a.lng],{icon:L.divIcon({className:'',html,iconSize:[size,size],iconAnchor:[size/2,size/2]}),zIndexOffset:selected?1000:0}).addTo(map);marker.bindTooltip(`${a.caller}<br/>${a.barangay}<br/>${a.dist} km`);marker.on('click',()=>onSelectAlert(a.id));markersRef.current[a.id]=marker;});if(selectedId){const a=alerts.find(x=>x.id===selectedId);if(a)map.flyTo([a.lat,a.lng],14,{duration:.35});}setTimeout(()=>map.invalidateSize(),50);};setup();return()=>{cancelled=true;};},[alerts,theme,selectedId,onSelectAlert]);
  useEffect(()=>()=>{if(mapInstanceRef.current){mapInstanceRef.current.remove();mapInstanceRef.current=null;}},[]);
  return <div ref={mapRef} className="w-full h-full bg-gray-100"/>;
}
